apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  gridIntensityProvider: {{ .Values.gridIntensity.provider }}
  gridIntensityRegion: {{ .Values.gridIntensity.region }}
