{{ if .Values.gridIntensity.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  apiToken: {{ .Values.gridIntensity.apiToken | b64enc | quote }}
{{ end }}
