name: kubernetes-integration-test
on: [push]
jobs:
  kubernetes-integration-test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Go build
        run: CGO_ENABLED=0 GOOS=linux go build .
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: localhost:5000/grid-intensity-exporter:integration-test
      - 
        name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
      - 
        name: Load image into Kind cluster
        run: kind load docker-image localhost:5000/grid-intensity-exporter:integration-test
      - 
        name: Set up Helm
        uses: azure/setup-helm@v1
      - 
        name: Helm install
        run: helm install grid-intensity-exporter helm/grid-intensity-exporter \
           --set image.repository=localhost:5000/grid-intensity-exporter,image.tag=integration-test
      - 
        name: Create port forward to the metrics port
        uses: kubectl port-forward deployment/grid-intensity-exporter 8000:8000
      - 
        name: Run integration test
        run: go test -v -tags=dockerrequired ./integration/test/docker
