name: nomad-integration-test
on: [push]
jobs:
  nomad-integration-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Go build
        run: CGO_ENABLED=0 GOOS=linux go build .
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: thegreenwebfoundation/grid-intensity-exporter:integration-test
      -
        name: Add HashiCorp GPG key
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      -
        name: Add HashiCorp Linux repository
        run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      -
        name: Install nomad
        run: sudo apt-get update && sudo apt-get install nomad
      -
        name: Start running nomad in agent mode, the background it
        run: nomad agent --dev &
      -
        name: Submit the grid-intensity-exporter.nomad job to nomad
        run: nomad run grid-intensity-exporter.nomad
      -
        name: Wait for job to start running, somehow
        uses: bash ./wait-for-nomad.sh
      -
        name: Run integration test
        run: go test -v -tags=dockerrequired ./integration/test/docker
